---
- name: install package signatures for Debian/Ubuntu
  apt_key:
    url: "{{ key_url }}/{{ key_item.1 }}"
    state: present
  when: key_item[0].packages == 'bce'
  loop: "{{ keys|subelements('packages_signatures') }}"
  loop_control:
    loop_var: key_item
  ignore_errors: true
