---
- include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-\
           {{ansible_userspace_bits}}_install_bce.yml"
  loop: "{{ query('first_found', params) }}"
