---
- name: get the temporary root password
  shell: "grep password /var/log/mysqld.log | awk '{ print $NF }'"
  register: root_temporary_password
  when: mysql_root_password not defined

- name: set the mysql_root_password
  set_fact:
    mysql_root_password: "{{ root_temporary_password.stdout }}"
  when: mysql_root_password is not defined

- name: set the temporary password as permanent
  command: MYSQL_PWD=\"{{ mysql_root_password }}\" mysql -u root --connect-expired-password --execute="ALTER USER 'root'@'localhost' identified by '{{ mysql_root_password }}';"
  when: mysql_root_password not defined
