---
- name: get the temporary root password
  shell: "grep password /var/log/mysqld.log | awk '{ print $NF }'"
  register: root_password
  when: mysql_root_password not defined
- name: set the temporary password as permanent
  command: "mysql -u root -p{{ root_password.stdout }} --connect-expired-password\
            --execute=\"ALTER USER 'root'@'localhost' identified by '{{ root_password.stdout }}';\""
  when: mysql_root_password not defined
