- name: Modify the Client name, if defined
  ansible.builtin.replace:
    path: /opt/bacula/etc/bacula-fd.conf
    after: 'FileDaemon {'
    regexp: "{{ client_hostname.split('.')[0] }}-fd"
    replace: "{{ client_name }}"  
  when: client_name is defined

- name: fail following tasks if director_hostname is not defined
  fail: msg="director_hostname not provided, skipping remote Director configuration."
  when: director_hostname is not defined

- name: create ansible.conf.d and ansible.conf.d/client directories, if they don't exist
  file:
    path: "{{ directories }}"
    state: directory
    mode: '0770'
    owner: root
    group: root
  loop:
    - /opt/bacula/etc/ansible.conf.d
    - /opt/bacula/etc/ansible.conf.d/client
  loop_control:
    loop_var: directories

- name: get the File Daemon password used to communicate with Director in the bacula-fd.conf file
  shell: "grep ^[[:space:]]*Password -m 1 /opt/bacula/etc/bacula-fd.conf | tr -d ' ' | tr -d '\"' | cut -d \"=\" -f2"
  register: current_fd_password

- name: set the dir_fd_password
  set_fact:
    dir_fd_password: "{{ current_fd_password.stdout }}"

- name: include director in the bacula-fd.conf file
  template:
    src: "director_conf_in_bacula_fd.j2"
    dest: "/opt/bacula/etc/ansible.conf.d/client/{{ director_name }}.conf"
    owner: root
    group: root
    mode: '0660'

- name: include the line to include the Director configuration in the ansible.conf.d directory in the bacula-fd.conf file
  blockinfile:
    path: /opt/bacula/etc/bacula-fd.conf
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Add Director {{ director_name }} in the bacula-fd.conf file"
    block: |
      @/opt/bacula/etc/ansible.conf.d/client/{{ director_name }}.conf
