- name: Modify the Client name, if defined
  ansible.builtin.replace:
    path: /opt/bacula/etc/bacula-fd.conf
    after: 'FileDaemon {'
    regexp: "{{ client_hostname.split('.')[0] }}-fd"
    replace: "{{ client_name }}"  
  when: client_name is defined

- name: fail following tasks if director_hostname is not defined
  fail: msg="director_hostname not provided, skipping remote Director configuration."
  when: director_hostname is not defined

- name: create ansible.conf.d directory
  file:
    path: /opt/bacula/etc/ansible.conf.d
    state: directory
    mode: '0770'
    owner: root
    group: bacula

- name: create empty file in the ansible.conf.d client directory
  file:
    path: /opt/bacula/etc/ansible.conf.d/empty.conf
    state: touch
    mode: '0770'
    owner: root
    group: bacula

- name: get the File Daemon password used to communicate with Director in the bacula-fd.conf file
  shell: "grep ^[[:space:]]*Password -m 1 /opt/bacula/etc/bacula-fd.conf | tr -d ' ' | tr -d '\"' | cut -d \"=\" -f2"
  register: current_fd_password

- name: set the dir_fd_password
  set_fact:
    dir_fd_password: "{{ current_fd_password.stdout }}"

- name: include the line to include all configuration files in the ansible.conf.d directory in the bacula-fd.conf file
  blockinfile:
    path: /opt/bacula/etc/bacula-fd.conf
    insertafter: EOF
    block: |
      @|"sh -c 'for f in /opt/bacula/etc/ansible.conf.d/*.conf ; do echo @${f} ; done'"

- name: include director in the bacula-fd.conf file
  template:
    src: "director_conf_in_bacula_fd.j2"
    dest: "/opt/bacula/etc/ansible.conf.d/{{ director_name }}.conf"
    owner: root
    group: bacula
    mode: '0660'
