- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}-repo.yml"
  loop_control:
    loop_var: repo_item
- name: Add BCE YUM repository
  yum_repository:
    name: "{{ repo_name }}"
    file: "{{ repo_filename }}"
    description: "{{ description }}"
    baseurl: "{{ dl_area }}/rpms/bin/{{ bce_version }}/{{ rhel_version }}-{{ architecture }}/"
    enabled: "{{ enabled }}"
    protect: "{{ protect }}"
    gpgcheck: "{{ gpgcheck }}"
