---
- name: create ansible.conf.d directory
  file:
    path: /opt/bacula/etc/ansible.conf.d/director
    state: directory
    mode: '0770'
    owner: bacula
    group: bacula
- name: copy any .conf file to the /opt/bacula/etc/ansible.conf.d/director directory
  copy:
    src: files/
    dest: /opt/bacula/etc/ansible.conf.d/director/
    mode: '0770'
    owner: bacula
    group: bacula
- name: include the line to include all configuration files in the ansible.conf.d directory in the bacula-dir.conf file
  blockinfile:
    path: /opt/bacula/etc/bacula-dir.conf
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - include any file in the bce role files directory"
    block: |
      @|"sh -c 'for f in /opt/bacula/etc/ansible.conf.d/director/*.conf ; do echo @${f} ; done'"
