---
# This task list will install the latest Bacula Community version
# available in the repository files added
# This will allow the upgrade of existent BCE install by
# adding the new repo file and using this same role to update
- name: install Bacula Enteprise Edition postgresql
  apt:
    name: bacula-postgresql
    state: present
  register: result
- debug: msg="{{ result.stderr.split('\n') }}"
  when: result.stderr is defined
