---
- name: Check if PostgreSQL database is initialized - check PGDATA is set
  shell: "sudo -Hiu postgres -- env | grep PGDATA"
  register: result_pgdata_se
- name: get PGDATA environment variable value for postgres user
  shell: "sudo -Hiu postgres bash -c 'echo $PGDATA'"
  register: result_pgdata_directory
  when: result_pgdata_set.rc == 0
- name: Check if PostgreSQL database is initialized - check if PG_VERSION directory exists
  stat:
    path: "{{ result_pgdata_directory.stdout }}/$PG_VERSION"
  register: result_PGDATA
  when: result_pgdata_directory.stdout != ""
- name: initialize PostgreSQL database
  shell: "postgresql-setup initdb"
  when: result_PGDATA.stat.exists
