---
- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ ansible_userspace_bits }}-repo.yml"
  loop_control:
    loop_var: repo_item
- name: Add BCE repository for CentOS hosts
  yum_repository:
    name: "{{ repo_name }}"
    file: "{{ repo_filename }}"
    description: "{{ description }}"
    baseurl: "{{ dl_area }}/rpms/{{ bce_version }}/{{ rhel_version }}/x86_64/"
    enabled: "{{ enabled }}"
    protect: "{{ protect }}"
    gpgcheck: "{{ gpgcheck }}"
