---
    - include_tasks: yum_upgrade_packages.yml
    - include_tasks: rpm-key_install_bce_keys.yml
    - include_tasks: yum-repository_add_repo_file.yml
    - include_tasks: yum_install_postgresql.yml
    - include_tasks: service_initialize_and_enable_postgresql.yml
    - include_tasks: yum_install_bce.yml
    - include_tasks: yum_list_packages_build.yml
    - include_tasks: service_start_postgresql.yml
    - include_tasks: All-platforms_create_bacula_database.yml
    - include_tasks: All-platforms_config_sdonly.yml
    - include_tasks: service_restart_sd.yml
    - include_tasks: All-platforms_config_sdonly_dir.yml
    - include_tasks: service_disable_stop_Director.yml
