---
- include_tasks: apt_update_package_manager.yml
- include_tasks: apt_install_additional_packages.yml
- include_tasks: apt-key_install_bce_keys.yml
- include_tasks: apt-repository_add_repo_file.yml
- include_tasks: apt_update_and_upgrade_packages.yml
- include_tasks: apt_install_postgresql.yml
- include_tasks: apt_install_bce.yml
- include_tasks: All-platforms_config_sdonly.yml
- include_tasks: systemd_start_bce_services.yml
- include_tasks: All-platforms_PostgreSQL_version.yml
- include_tasks: All-platforms_BCE_check_director_status.yml
- include_tasks: All-platforms_BCE_check_FD_status.yml
- include_tasks: All-platforms_BCE_check_SD_status.yml
- include_tasks: apt_list_packages_build.yml
