---
- name: Check if PostgreSQL database is initialized
  stat:
    path: "{{ result_pgdata_directory.stdout }}/PG_VERSION"
  register: result_pgdata
- name: start postgresql server
  service:
    name: postgresql
    state: started
  when: result_pgdata.stat.exists
