---
- name: Check if PostgreSQL database is initialized (PGDATA is set)
  shell: "sudo -Hiu postgres -- env | grep PGDATA"
  register: result_pgdata_set
- name: get PGDATA environment variable value for postgres user
  shell: "sudo -Hiu postgres bash -c 'echo $PGDATA'"
  register: result_pgdata_directory
  when: result_pgdata_set.rc == 0
- name: Check if PostgreSQL database is initialized (PG_VERSION dir exists)
  stat:
    path: "{{ result_pgdata_directory.stdout }}/PG_VERSION"
  register: result_PGDATA
  when: result_pgdata_directory.stdout != ""
- name: initialize PostgreSQL database
  shell: "service postgresql initdb"
  when: not result_PGDATA.stat.exists
- name: set the PostgreSQL database to auto-start at boot
  service:
    name: postgresql
    enabled: true
