---
- name: Check if PostgreSQL database is initialized (PG_VERSION dir exists)
  stat:
    path: "{{ result_pgdata_directory.stdout }}/PG_VERSION"
  register: result_PGDATA
- name: start postgresql server
  service:
    name: postgresql
    state: started
  when: result_PGDATA.stat.exists
