---
    - include_tasks: zypper_update_and_upgrade_packages.yml
    - include_tasks: zypper-repository_add_repo_file.yml
    - include_tasks: zypper_install_postgresql.yml
    - include_tasks: zypper_install_bce.yml
    - include_tasks: zypper_list_packages_build.yml
    - include_tasks: systemd_start_postgresql.yml
    - include_tasks: All-platforms_create_bacula_database.yml
    - include_tasks: All-platforms_config_sdonly.yml
    - include_tasks: systemd_restart_sd.yml
    - include_tasks: All-platforms_config_sdonly_dir.yml
    - include_tasks: systemd_disable_stop_Director.yml
