---
- name: restart bacula-sd service
  systemd:
    name: bacula-sd
    state: restarted
  ignore_errors: true
- name: Short delay before checking Storage Daemon status
  wait_for:
    timeout: 10
- name: check bacula-sd daemon status
  shell: systemctl status bacula-sd
  register: bacula_sd_status
  ignore_errors: true
- debug: msg="{{ bacula_sd_status.stdout.split('\n') }}"
- debug: msg="{{ bacula_sd_status.stderr.split('\n') }}"
