---
- name: stop bacula-dir service
  systemd:
    name: bacula-dir
    enabled: false
    state: stopped
- name: check bacula-dir daemon status
  command: systemctl status bacula-dir
  register: bacula_dir_status
  ignore_errors: true
- debug: msg="{{ bacula_dir_status.stdout.split('\n') }}"
- debug: msg="{{ bacula_dir_status.stderr.split('\n') }}"
