---
- name: get list of packages installed
  yum:
    list=installed
  register: yum_packages
- name: list bacula community packages builds
  debug:
    msg: "{{ yum_packages | json_query(query_packages) }}"
  vars:
    query_packages: "results[?name == 'bacula-postgresql']"
